version: '3'
services:
  web:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "9090:80"
    networks:
      - com-net 
       
  db:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=1234
    volumes: 
      - mysql_volume:/var/lib/mysql
    networks:
      - com-net 
volumes:
  mysql_volume:
   
networks: 
  com-net:
