version: '3'
services:
  web:
    container_name: wordpress
    image: wordpress
    ports:
      - "9090:80"
    networks:
      - wpnet  
    volumes:
      - "$pwd/wpdate:/var/www/html"  
    environment: 
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress  
    depends_on: 
      - db  

  db:
    container_name: wpmysql
    image: mysql:5.7 
    ports:
      - "3306:3306"
    networks:
      - wpnet
    volumes:
      - wpvolume:/var/lib/mysql 
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wordpress 
      MYSQL_USER: wordpress 
      MYSQL_PASSWORD: wordpress  
networks:
  wpnet:
volumes:
  wpvolume: